.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DETROIT\-DNOTE" "5" "October 2011" "" ""
.
.SH "NAME"
\fBdetroit\-dnote\fR \- extract developers notes from ruby source code
.
.SH "DESCRIPTION"
The DNote plug\-in for Detroit utilize the DNote command line tool to extract notes from source code and construct nicely formated documentation out of it\.
.
.SH "OPTIONS"
The following options can be used in the Detroit assembly file for defining a dnote service\.
.
.IP "\(bu" 4
\fBlabels\fR \- List of labels to document\. The default list includes \fBTODO\fR, \fBFIXME\fR, \fBOPTIMIZE\fR, and \fBDEPRECATE\fR\.
.
.IP "\(bu" 4
\fBfiles\fR \- File paths to search\.
.
.IP "\(bu" 4
\fBexclude\fR \- Exclude paths\.
.
.IP "\(bu" 4
\fBignore\fR \- Ignore paths based on any part of pathname\.
.
.IP "\(bu" 4
\fBtitle\fR \- Title to use if template can use it\.
.
.IP "\(bu" 4
\fBlines\fR \- Number of context lines to display\.
.
.IP "\(bu" 4
\fBoutput\fR \- Output is either a file name with a recognized extension, a list of such file names, or a hash mapping file name to file type\. Recognized extensions include \fBxml\fR, \fBhtml\fR and \fBrdoc\fR among others\.
.
.IP "" 0
.
.SH "EXAMPLES"
The simplist entry is
.
.IP "" 4
.
.nf

dnote:
  output: NOTES\.rdoc
.
.fi
.
.IP "" 0
.
.P
To produce multiple formats use a list\.
.
.IP "" 4
.
.nf

dnote:
  output:
    \- NOTES\.rdoc
    \- site/notes\.html
.
.fi
.
.IP "" 0
.
.P
If the extension is atypical use a mapping\.
.
.IP "" 4
.
.nf

 dnote:
   output:
     NOTES: markdown
     site/notes\.html: html
.
.fi
.
.IP "" 0
.
.P
A fuller example might look something like this\.
.
.IP "" 4
.
.nf

 dnote:
   labels: [TODO, THINK, FIX]
   files: [lib, test]
   exclude:
     \- lib/foo/templates
   ignore: [\.yml]
   output: log/NOTES\.rdoc
   lines: 5
.
.fi
.
.IP "" 0
.
.SH "RESOURCES"
For more information:
.
.IP "\(bu" 4
API Documentation \fIhttp://rubydoc\.info/gems/detroit\-dnote\fR
.
.IP "\(bu" 4
Development Site \fIhttp://github\.com/detroit/detroit\-dnote\fR
.
.IP "" 0
.
.SH "COPYRIGHT"
Copyright (c) 2010 Thomas Sawyer, Rubyworks
.
.P
Detroit DNote is distributable in accordance with the GPLv3 license\.
.
.SH "SEE ALSO"
dnote(1)
